#:schema https://mise.jdx.dev/schema/mise.json
[tools]
ast-grep = "latest"
awscli = "latest"
cargo-binstall = "latest"
claude-code = "latest"
difftastic = "latest"
dive = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
git-lfs = "latest"
github-cli = "latest"
"github:docker/sbx-releases" = "latest"
glow = "latest"
jj = "latest"
jq = "latest"
neovim = "0.11"
ripgrep = "latest"
tree-sitter = "0.25.3"
usage = "latest"
uv = "latest"
yq = "latest"

[settings]
experimental = true
lockfile = true
python.uv_venv_auto = false

[env]
_.path = [
  "~/.local/share/mise/shims",
  "~/Library/pnpm",
  "~/.local/share/pnpm",
  "~/.local/bin",
  "~/.cargo/bin",
  "~/go/bin",
]

[shell_alias]
ll = "ls -la"
gco = "git checkout"
gs = "git status"
gcb = "git checkout -b"
gll = "git log"
