[tools]
ast-grep = "latest"
cargo-binstall = "latest"
difftastic = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
jj = "0.34"
jq = "latest"
neovim = "0.11"
node = "24"  # for codex/claude code
pnpm = "latest"  # for codex/claude code
ripgrep = "latest"
tree-sitter = "0.25.3"
usage = "latest"
uv = "latest"
yq = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"

[settings]
experimental = true
lockfile = true
python.uv_venv_auto = false

[env]
_.path = [
  "~/.local/share/mise/shims",
  "~/Library/pnpm",
  "~/.local/share/pnpm",
  "~/.local/bin",
  "~/.cargo/bin",
  "~/go/bin",
]
