[tools]
ast-grep = "latest"
cargo-binstall = "latest"
chezmoi = "latest"
difftastic = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
go = "latest"
jj = "latest"
jq = "latest"
neovim = "0.11.2"
node = "22"
pnpm = "latest"
ripgrep = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
"npm:@anthropic-ai/claude-code" = "latest"

[settings]
experimental = true
lockfile = true
python.uv_venv_auto = false

[env]
_.path = [
  "~/.local/share/mise/shims",
  "~/Library/pnpm",
  "~/.local/share/pnpm",
  "~/.cargo/bin",
  "~/go/bin",
  "~/.local/bin",
  "/opt/homebrew/bin",
]
