return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    branch = "master",
    lazy = false,
    config = function()
        require("nvim-treesitter.configs").setup {
            ensure_installed = {
                "bash",
                "c",
                "css",
                "dockerfile",
                "gitignore",
                "go",
                "gotmpl",
                "html",
                "javascript",
                "json",
                "jsonc",
                "make",
                "markdown",
                "markdown_inline",
                "python",
                "query",
                "rust",
                "sql",
                "starlark",
                "terraform",
                "toml",
                "tsx",
                "typescript",
                "vim",
                "vimdoc",
                "yaml",
                "zig",
            },
            sync_install = false,
            auto_install = true,
            ignore_install = { "lua" },
            highlight = {
                enable = true,
                disable = { "lua" },
            },
        }
    end
}
